### ISSUE TITLE
Latest version not on NPM

### ISSUE THREAD

**Issue by Harkunwar** [akira-cn/node-canvas-webgl#12]
Hello.

Thank you for the amazing work on this project. I wanted to use the changes, such as #11 as fixes for my project. Could you publish the latest release to npm as well?

**Comment by akira-cn** [comment]
> Hello.
> 
> Thank you for the amazing work on this project. I wanted to use the changes, such as #11 as fixes for my project. Could you publish the latest release to npm as well?

done
