### ISSUE TITLE
npm package isn't up to date

### ISSUE THREAD

**Issue by animanathome** [akira-cn/node-canvas-webgl#7]
The latest package `0.2.6` doesn't contain the latest code changes. The following line, for instance,
https://github.com/akira-cn/node-canvas-webgl/blob/master/lib/canvas.js#L108, is different and is currently causing an error. It reads ```if(pixels._image) pixels = pixels._image;``` instead of ```if(pixels && pixels._image) pixels = pixels._image;``` Is it possible to release a new npm package with the latest, up-to-date changes? Thanks.

**Comment by akira-cn** [comment]
update to 0.2.7
